#!/usr/local/bin/bash

iter=$(cat iter.txt)
new=$(($iter+1))

> iter.txt
echo $new > iter.txt

if [ $new -le 3 ]
then
        echo "running benchmark iteration $new"
        cd ./src
        sudo ./run_benchmarks $1
        cd ..
        sudo reboot
fi
