#!/usr/local/bin/bash

readarray -t partitions < ./valid_partitions.txt

version=$(uname -r)
curr_id=$(gpart show -l | grep bootme | awk '{print $3}')

for index in ${!partitions[*]}; 
do
	if [ ${partitions[$index]} -eq $curr_id ]
	then
		break
	fi
done

next_id=$(($index+1))

gpart set -a bootme -i $next_id ada0
gpart unset -a bootme -i $curr_id ada0

cd ./src
sudo ./run_benchmarks "TEST-13.0" 
cd ..
