#!/usr/local/bin/bash

readarray -t partitions < ./valid_partitions.txt

version=$(uname -r)
curr_id=$(gpart show -l | grep bootme | awk '{print $3}')

for index in ${!partitions[*]}; 
do
	if [ ${partitions[$index]} -eq $curr_id ]
	then
		break
	fi
done

next_id=$(($index+1))

echo $next_id
echo "$index"

echo ${partitions[2]}

cd ./src
sudo ./run_benchmarks "$version" 
cd ..
